### ISSUE TITLE
Request from AirMonitor

### ISSUE THREAD

**Issue by airmonitor** [hackerspace-silesia/Smogomierz#100]
Cześć Błażej,

Dałbyś radę wrzucić do następnej wersji interwał przesyłania danych do API AirMonitora na minimalną wartość 30 minut?

Najlepiej tez jitter aby rozłożyć workload między 60 a 300 sekund.

Czyli każda stacja wysyłałaby metryki co 30 minut +- 60 do 300 sekund.

**Comment by bfaliszek** [comment]
Dodałem w kodzie minimalną wartość interwału dla AirMonitora to 30 minut. Jedynie w przypadku włączonego DEEPSLEEP w ESP może być inna, bo jest wtedy uzależniona od tego kiedy wybudza się samo ESP. https://github.com/hackerspace-silesia/Smogomierz/commit/7d805e06e04d6a713c66249dad52816e125c2440
