### ISSUE TITLE
Padł PMS?

### ISSUE THREAD

**Issue by tnowak** [hackerspace-silesia/Smogomierz#102]
Zanim napiszę do Botlandu w sprawie reklamacji, chciałem się tu upewnić czy dobrze wszystko widzę.
Po ok 2.5 miesiącach dobrej pracy wygląda na to ze padł mi czujnik PMS 7003 (kupowałem go w zestawie). Cały czas pokazuje pomiary 0 µg/m³. Tak to wygląda w smogly:

![image](https://user-images.githubusercontent.com/54801553/84883882-633e5f80-b091-11ea-9705-0f802dfcd3af.png)

Co dokładnie znaczy 0 w kolorze cyan?
Czy te wykresy na dole oznaczają, że on coś tam jednak mierzy? (niby są wartości pomiędzy 0 i 1)

Choć powietrze jest ostanio dobrej jakości, to jednak nie dałem wiary że non stop doskonałej. Wziąłem czujnik do domu i rozpyliłem jakiś aerozol w pobliżu. Pomiar na czujniku PM w oczyszczaczu powietrza Xiaomi poleciał w kosmos, a pomiar na PMS - nie ruszył się nawet.

Popsuł się, reklamować?

**Comment by bfaliszek** [comment]
Jeśli nawet w domu przy aerozolu lub dymie ze świeczki/zapałki wciąż pokazuje 0, to chyba nie działa.
Kolory są uzależnione od poziomu PM, jeśli wartość wynosi 0, to oznacza, że jest wyświetlana w kolorze idealnie czystego powietrza ;)

Przed wysłaniem możesz jeszcze sprawdzić czy wszystko ok z kablami z PMS. Czasami z nimi jest problem.

**Comment by tnowak** [comment]
Błażej, dziękuję Ci za jak zwykle celne rady. Miałeś rację - najwyraźniej był jakiś problemik z kabelkami. Otworzyłem obudowę, wpiąłem wszystkie jeszcze raz i:

![image](https://user-images.githubusercontent.com/54801553/84885756-c5985f80-b093-11ea-83de-7772a5e2e91b.png)

:)
