### ISSUE TITLE
metrics.airmonitor.pl - Witryna nie istnieje

### ISSUE THREAD

**Issue by jarekera** [hackerspace-silesia/Smogomierz#107]
Witam, od dłuższego czasu na stronie smogomierza do serwisów Airminitor jest komunikat:
"Nie udało się nawiązać połączenia
Firefox nie może nawiązać połączenia z serwerem metrics.airmonitor.pl:3000. 
"
były już aktualizacje od czasu wystąpienia, ale problem jest w dalszym ciągu.
Na stronie Airmonitor dane pokazują się poprawnie, ale widzę że chyba zmienił się adres strony prezentujący te mierniki brak numeru portu, czy możecie to poprawić ?

**Comment by bfaliszek** [comment]
Gdy tylko znajdę chwilę czasu. Ewentualnie możesz zrobić PR z tą zmianą.

**Comment by jarekera** [comment]
Aż tak oblatany w tym nie jestem. Ok poczekam jak będzie poprawka jakaś.

**Comment by galuszkak** [comment]
@bfaliszek @jarekera wrzuciłem PRa z poprawką w #108

**Comment by jankes46** [comment]
a jak te poprawki wgrać ?
muszę podłączyć arduino po kablu czy da się po wifi ?
przepraszam za takie pytania ale dopiero zaczynam zabawę z Arduino

**Comment by bfaliszek** [comment]
@jankes46 jeśli masz urządzenie oparte o ESP8266 i miernik PMS7003 lub PMS5003 to możesz wgrać przez przeglądarkę plik .bin. Właśnie wrzuciłem skompilowaną wersję z poprawką dodaną przez @galuszkak - https://github.com/hackerspace-silesia/Smogomierz/blob/dev/firmware/ESP8266/prerelease_ESP8266_Smogomierz_2.8.0_PMS_build_2.12.2020.bin

**Comment by jarekera** [comment]
Dzięki działa

**Comment by jankes46** [comment]
A jeszcze jedno czy na stronie powinienem widzieć wykres czy to będzie za jakiś czas od uruchomienia ?
![image](https://user-images.githubusercontent.com/75259553/100926046-1802f680-34e3-11eb-8dff-f9e8e74972a3.png)

**Comment by jarekera** [comment]
On uśrednia wyniki i pojawia się z opóźnieniem, ale jak poprawnie skonfigurowałeś cos takiego zobaczyć na stronie airmonitor - [https://metrics.airmonitor.pl/d/000000002/airmonitor?orgId=1&var-latitude=52.315742&var-longitude=21.138281&from=now-24h&to=now&refresh=10s](url)

**Comment by jankes46** [comment]
jest tak:
https://metrics.airmonitor.pl/d/000000002/airmonitor?orgId=1&from=now-24h&to=now&refresh=10s&var-latitude=52.315742&var-longitude=19.433179

**Comment by jarekera** [comment]
Wyglada ze nie wysyłasz danych do Airmonitor przejrzyj jeszcze ustawienia i
sprawdź czy się zarejestrowałeś w Airmonitor.

<goog_1659957815>
Instrukcja -
https://github.com/hackerspace-silesia/Smogomierz/blob/master/instrukcje/software-additionals.md

[image: obraz.png]


Pozdrawiam JZ

śr., 2 gru 2020 o 21:30 jankes46 <notifications@github.com> napisał(a):

**Comment by artur5236** [comment]
> @jankes46 jeśli masz urządzenie oparte o ESP8266 i miernik PMS7003 lub PMS5003 to możesz wgrać przez przeglądarkę plik .bin. Właśnie wrzuciłem skompilowaną wersję z poprawką dodaną przez @galuszkak - https://github.com/hackerspace-silesia/Smogomierz/blob/dev/firmware/ESP8266/prerelease_ESP8266_Smogomierz_2.8.0_PMS_build_2.12.2020.bin

Link nie działa. 
Ja po uruchomieniu Smogly ma coś takiego:
![image](https://user-images.githubusercontent.com/19570333/105047664-e3cf9f00-5a6a-11eb-8dc5-ba6c4241068c.png)

**Comment by bfaliszek** [comment]
Link nie działa, to jest nowszy build - https://github.com/hackerspace-silesia/Smogomierz/tree/dev/firmware/ESP8266
