### ISSUE TITLE
Problem z kompilacją na ESP32

### ISSUE THREAD

**Issue by ebuke** [hackerspace-silesia/Smogomierz#109]
cześć,
Mam problem z kompilacją na płytce ESP32. Ktoś ma pomysł o co chodzi? 

wysypuje się na linii 875
#elif defined ARDUINO_ARCH_ESP32
    sprintf(device_name, "Smogly-%06X", ESP.getEfuseMac());

exit status 1
comparison with string literal results in unspecified behaviour [-Werror=address]

**Comment by bfaliszek** [comment]
Hej! 
Użyłeś kodu z dev? https://github.com/hackerspace-silesia/Smogomierz/tree/dev
Zmieniałeś coś w nim? Jaką masz ustawioną płytkę ESP32 w ArduinoIDE? Ja kompiluję zawsze na ESP32 Dev Module

**Comment by ebuke** [comment]
Hej. Kod mam z mastera. Nic nie zmieniałem. Kompiluję też na ESP32 DEV Module. Może brakuje mi którejś biblioteki poza tymi które są w instrukcji?

**Comment by ebuke** [comment]
Winne ustawienia ostrzeżeń kompilatora. Były za wysokie.
