### ISSUE TITLE
błędy w danych dot. ciśnienia

### ISSUE THREAD

**Issue by CoolTechProjects** [hackerspace-silesia/Smogomierz#114]
Dzień dobry,
zauważyłem że smogly (moja wersja oprogramowania: 2.7.9 PMS) poprawnie odczytuje ciśnienie z czujnika BME280, wysyła je również poprawnie do ThingSpeak, natomiast w przypadku aqi.eco dane są niepoprawne, zawyżone o kilkaset hPa..
Po analizie JSONów odbieranych po stronie aqi.eco zauważyłem prawdopodobny błąd, przesunięcie przecinka o 2 miejsca dla pola pressure..
Lokalny odczyt Smogly pokazuje 1007 hPa, odczyt po stronie aqi.eco pokazuje 1045 hPa..

> 2021-04-07 09:28:05 | {"esp8266id":"14825363","software_version":"Smogly_2.7.9 build 19:42:03 May 3 2020","sensordatavalues":[{"value_type":"PMS_P0","value":0},{"value_type":"PMS_P1","value":0},{"value_type":"PMS_P2","value":0},{"value_type":"BME280_temperature","value":"3.30"},{"value_type":"BME280_humidity","value":"58.98"},{"value_type":"BME280_pressure","value":"100764.66"}]}

Pytanie czy mogę to poprawić we własnym zakresie czy wymagana jest poprawka w kolejnej aktualizacji?

z góry dziękuję za pomoc
Adam

**Comment by bfaliszek** [comment]
https://github.com/hackerspace-silesia/Smogomierz/issues/74
