### ISSUE TITLE
Problem z InfluxDB

### ISSUE THREAD

**Issue by imielowskia** [hackerspace-silesia/Smogomierz#115]
Na początek słowa uznania za udany projekt. 
Ale niestety pojawił się drobny bug: aktualnie InfluxDB 2 używa tokenów o długości 88 znaków - zmienna zadeklarowana dla tokena ma 64 i nie działa przesyłanie do bazy. Drobiazg prosty do poprawienia, ja sobie poradziłem (trochę grzebnąłem w kodzie) ale warto poprawić dla innych,
pozdrawiam

**Comment by bfaliszek** [comment]
Hej!
Dzięki za info. Zwiększyłem maksymalną długość tokenów na 128 znaków - https://github.com/hackerspace-silesia/Smogomierz/commit/19f8a3adaeaeab538e0d723de2ccc1a3b1a45a4f
