### ISSUE TITLE
Problem z zasilaniem

### ISSUE THREAD

**Issue by BartekMilew** [hackerspace-silesia/Smogomierz#118]
Czy ktoś może wie w czym moze być problem? Podłączam kabel USB do ESP8266 bezpośrednio i wszystko hula. Jak podłączę przez wtyczkę micro USB jak w projekcie to nie działa. Wymieniałem już wtyczke i kabel. Nadal nic.
![243674580_896869784599779_3860042806272071366_n](https://user-images.githubusercontent.com/40686395/135654939-8e2c1e8f-2eb3-47be-902e-1049fcd166e7.jpg)
![243353405_300021604817873_715525842273435054_n](https://user-images.githubusercontent.com/40686395/135654954-5e169556-4ab9-41f6-8ad5-088652596393.jpg)

**Comment by bfaliszek** [comment]
Sprawdź inne G na płytce ESP8266

**Comment by BartekMilew** [comment]
Działa !!! Nie wiem czemu tak, ale super !

**Comment by bfaliszek** [comment]
W niektórych chińskich esp8266 nie działa G przy VIN. Nie wiem z jakiego powodu, ale raz na ileś przypadków trafia mi się takie esp8266 😉
