### ISSUE TITLE
Konfiguracja źródeł.

### ISSUE THREAD

**Issue by krapit** [hackerspace-silesia/Smogomierz#12]
W jaki sposób należy skonfigurować (/sparametryzować) udostępnione źródła aby otrzymać binarkę zgodną z wersją: "Smogomierz_2.4.9_PMS-SparkFunBME280" ?

**Comment by bfaliszek** [comment]
Wersja SparkFunBME28.bin różni się od "zwykłej" tylko adresem I2C dla miernika BME280. Cała reszta kodu jest identyczna. 

Ta linijka jest zakomentowana, a poniższa odkomentowana ;) 
https://github.com/hackerspace-silesia/Smogomierz/blob/32547c4d5ad92c089f5f6b8a1e9c0799e81c5bd8/src/bme280.h#L18
