### ISSUE TITLE
nie działa CSS na stronie WWW smogomierza

### ISSUE THREAD

**Issue by krupniok200** [hackerspace-silesia/Smogomierz#148]
Nie potrafi się załadować kaskadowy arkusz stylów strony WWW smogomierza. Po przejrzeniu kody zauważyłem, że strona na której znajduje się plik CSS "https://raw.githack.com/hackerspace-silesia/Smogomierz/master/src/css/smogly.css" nie istnieje, czyli wyskakuje błąd 404.

**Comment by bfaliszek** [comment]
Pobierz jeszcze raz bin i zaktualizuj firmware - https://github.com/hackerspace-silesia/Smogomierz/releases/tag/v2.8.1
W pierwszej wersji był podany błędny adres. Już to poprawiłem.
