### ISSUE TITLE
temperatura i wilgotność w homebridge

### ISSUE THREAD

**Issue by straubus** [hackerspace-silesia/Smogomierz#15]
Moi drodzy, świetny projekt, ale czy da się dane z bme280 wyciągnąć do homebridge tak samo jak status o jakości powietrza?
Znalazłem taki plugin, 
https://www.npmjs.com/package/homebridge-http-humidity      i taki https://www.npmjs.com/package/homebridge-http-temperature, i wyciąga dane ze smogomierz.local/api... ale to nadal dwa dodatkowe pluginy, może da się to dorzucić do głównego?

**Comment by bfaliszek** [comment]
Plugin do homebridge jest w moim repo i jest tam już wątek rozbudowy: https://github.com/bfaliszek/homebridge-smogomierz/issues/1
Gdy znajdę trochę czasu to postaram się rozbudować tę wtyczkę.

**Comment by mientki** [comment]
Niestety po aktualizacji wtyczka nie działa :(


 

> Feb 13 21:09:28 homebridge homebridge[10273]: [2019-2-13 21:09:28] [Parking Jakość powietrza] Smogomierz is working
> Feb 13 21:09:28 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
> Feb 13 21:09:28 homebridge systemd[1]: homebridge.service: Unit entered failed state.
> Feb 13 21:09:28 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.

`

**Comment by bfaliszek** [comment]
Wszystkie sprawy związane z wtyczką homebridge najlepiej omawiać w repo tej wtyczki: https://github.com/bfaliszek/homebridge-smogomierz/issues
