### ISSUE TITLE
Błąd typu dla channel id dla thing speak

### ISSUE THREAD

**Issue by zibu-dev** [hackerspace-silesia/Smogomierz#156]
Dla pola THINGSPEAK_CHANNEL_ID ustawiony jest typ unsigned short, który jest nie wystarczający dla obecnie generowanych wartości przy zakładaniu kanału na thing speak np 1646052

**Comment by bfaliszek** [comment]
Poprawiłem na unsigned int
https://github.com/hackerspace-silesia/Smogomierz/commit/58c10e9576bf2b0f5b6f1c4cb81623e6e717e787
