### ISSUE TITLE
Smogomierz nie podaje danych z BME280 cd.

### ISSUE THREAD

**Issue by opennas** [hackerspace-silesia/Smogomierz#16]
Mam czujnik BME280 wilgotności temperatury oraz ciśnienia i podłączony mam 4 kabelkami z wykorzystaniem SCL i SDA.

Zgodnie z rekomendacją wdo sprawdzenia adresu BME280 wykorzystałem kod https://playground.arduino.cc/Main/I2cScanner i zmieniłem Serial.begin(9600); na Serial.begin(115200);

Zmieniłem na nowy zarówno kontroler NodeMCU v3 + moduł WiFi ESP8266 jak i również czujnik BME280. Wszystko połączone jest zgodnie ze schematem i opisem.

Nie wiem co może być przyczyną tego problemu i proszę o pomoc, bo chwilowo wyczerpały mi się pomysły.

20:16:21.928 -> Scanning...
20:16:21.928 -> Unknown error at address 0x01
20:16:21.928 -> Unknown error at address 0x02
20:16:21.928 -> Unknown error at address 0x03
20:16:21.962 -> Unknown error at address 0x04
20:16:21.962 -> Unknown error at address 0x05
20:16:21.962 -> Unknown error at address 0x06
20:16:21.962 -> Unknown error at address 0x07
20:16:21.962 -> Unknown error at address 0x08
20:16:21.962 -> Unknown error at address 0x09
20:16:21.962 -> Unknown error at address 0x0A
20:16:21.962 -> Unknown error at address 0x0B
20:16:21.962 -> Unknown error at address 0x0C
20:16:21.962 -> Unknown error at address 0x0D
20:16:21.962 -> Unknown error at address 0x0E
20:16:21.962 -> Unknown error at address 0x0F
20:16:21.962 -> Unknown error at address 0x10
20:16:21.995 -> Unknown error at address 0x11
20:16:21.995 -> Unknown error at address 0x12
20:16:21.995 -> Unknown error at address 0x13
20:16:21.995 -> Unknown error at address 0x14
20:16:21.995 -> Unknown error at address 0x15
20:16:21.995 -> Unknown error at address 0x16
20:16:21.995 -> Unknown error at address 0x17
20:16:21.995 -> Unknown error at address 0x18
20:16:21.995 -> Unknown error at address 0x19
20:16:21.995 -> Unknown error at address 0x1A
20:16:21.995 -> Unknown error at address 0x1B
20:16:21.995 -> Unknown error at address 0x1C
20:16:22.029 -> Unknown error at address 0x1D
20:16:22.029 -> Unknown error at address 0x1E
20:16:22.029 -> Unknown error at address 0x1F
20:16:22.029 -> Unknown error at address 0x20
20:16:22.029 -> Unknown error at address 0x21
20:16:22.029 -> Unknown error at address 0x22
20:16:22.029 -> Unknown error at address 0x23
20:16:22.029 -> Unknown error at address 0x24
20:16:22.029 -> Unknown error at address 0x25
20:16:22.029 -> Unknown error at address 0x26
20:16:22.029 -> Unknown error at address 0x27
20:16:22.029 -> Unknown error at address 0x28
20:16:22.063 -> Unknown error at address 0x29
20:16:22.063 -> Unknown error at address 0x2A
20:16:22.063 -> Unknown error at address 0x2B
20:16:22.063 -> Unknown error at address 0x2C
20:16:22.063 -> Unknown error at address 0x2D
20:16:22.063 -> Unknown error at address 0x2E
20:16:22.063 -> Unknown error at address 0x2F
20:16:22.063 -> Unknown error at address 0x30
20:16:22.063 -> Unknown error at address 0x31
20:16:22.063 -> Unknown error at address 0x32
20:16:22.063 -> Unknown error at address 0x33
20:16:22.063 -> Unknown error at address 0x34
20:16:22.063 -> Unknown error at address 0x35
20:16:22.097 -> Unknown error at address 0x36
20:16:22.097 -> Unknown error at address 0x37
20:16:22.097 -> Unknown error at address 0x38
20:16:22.097 -> Unknown error at address 0x39
20:16:22.097 -> Unknown error at address 0x3A
20:16:22.097 -> Unknown error at address 0x3B
20:16:22.097 -> Unknown error at address 0x3C
20:16:22.097 -> Unknown error at address 0x3D
20:16:22.097 -> Unknown error at address 0x3E
20:16:22.097 -> Unknown error at address 0x3F
20:16:22.097 -> Unknown error at address 0x40
20:16:22.097 -> Unknown error at address 0x41
20:16:22.130 -> Unknown error at address 0x42
20:16:22.130 -> Unknown error at address 0x43
20:16:22.130 -> Unknown error at address 0x44
20:16:22.130 -> Unknown error at address 0x45
20:16:22.130 -> Unknown error at address 0x46
20:16:22.130 -> Unknown error at address 0x47
20:16:22.130 -> Unknown error at address 0x48
20:16:22.130 -> Unknown error at address 0x49
20:16:22.130 -> Unknown error at address 0x4A
20:16:22.130 -> Unknown error at address 0x4B
20:16:22.130 -> Unknown error at address 0x4C
20:16:22.130 -> Unknown error at address 0x4D
20:16:22.130 -> Unknown error at address 0x4E
20:16:22.130 -> Unknown error at address 0x4F
20:16:22.164 -> Unknown error at address 0x50
20:16:22.164 -> Unknown error at address 0x51
20:16:22.164 -> Unknown error at address 0x52
20:16:22.164 -> Unknown error at address 0x53
20:16:22.164 -> Unknown error at address 0x54
20:16:22.164 -> Unknown error at address 0x55
20:16:22.164 -> Unknown error at address 0x56
20:16:22.164 -> Unknown error at address 0x57
20:16:22.164 -> Unknown error at address 0x58
20:16:22.164 -> Unknown error at address 0x59
20:16:22.164 -> Unknown error at address 0x5A
20:16:22.164 -> Unknown error at address 0x5B
20:16:22.198 -> Unknown error at address 0x5C
20:16:22.198 -> Unknown error at address 0x5D
20:16:22.198 -> Unknown error at address 0x5E
20:16:22.198 -> Unknown error at address 0x5F
20:16:22.198 -> Unknown error at address 0x60
20:16:22.198 -> Unknown error at address 0x61
20:16:22.198 -> Unknown error at address 0x62
20:16:22.198 -> Unknown error at address 0x63
20:16:22.198 -> Unknown error at address 0x64
20:16:22.198 -> Unknown error at address 0x65
20:16:22.198 -> Unknown error at address 0x66
20:16:22.198 -> Unknown error at address 0x67
20:16:22.233 -> Unknown error at address 0x68
20:16:22.233 -> Unknown error at address 0x69
20:16:22.233 -> Unknown error at address 0x6A
20:16:22.233 -> Unknown error at address 0x6B
20:16:22.233 -> Unknown error at address 0x6C
20:16:22.233 -> Unknown error at address 0x6D
20:16:22.233 -> Unknown error at address 0x6E
20:16:22.233 -> Unknown error at address 0x6F
20:16:22.233 -> Unknown error at address 0x70
20:16:22.233 -> Unknown error at address 0x71
20:16:22.233 -> Unknown error at address 0x72
20:16:22.233 -> Unknown error at address 0x73
20:16:22.233 -> Unknown error at address 0x74
20:16:22.266 -> Unknown error at address 0x75
20:16:22.266 -> Unknown error at address 0x76
20:16:22.266 -> Unknown error at address 0x77
20:16:22.266 -> Unknown error at address 0x78
20:16:22.266 -> Unknown error at address 0x79
20:16:22.266 -> Unknown error at address 0x7A
20:16:22.266 -> Unknown error at address 0x7B
20:16:22.266 -> Unknown error at address 0x7C
20:16:22.266 -> Unknown error at address 0x7D
20:16:22.266 -> Unknown error at address 0x7E
20:16:22.266 -> No I2C devices found
20:16:22.266 ->

**Comment by bfaliszek** [comment]
Wygląda jakby BME280 było uszkodzone

**Comment by firemark** [comment]
Pytanie durne - czy dobrze podłączyłeś zasilanie? :)

**Comment by bfaliszek** [comment]
a sprawdź na D1 i D2? Jeśli samemu kompilujesz kod w ArduinoIDE to daj znać też jaką masz wersję ESP8266core najnowsza to 2.5.0 beta 3 i w tych betach może coś nie działać(np. SoftwareSerial).

**Comment by opennas** [comment]
Po odłączeniu D1 i D2 z projektu Smogomierz i podłączeniu BME280

VCC - 3V
GND - G
SCL - D2
SDA - D1

nie wykrywał nic.

```
22:30:30.391 -> Scanning...
22:30:30.425 -> No I2C devices found
22:30:30.425 -> 
22:30:35.402 -> Scanning...
22:30:35.435 -> No I2C devices found
22:30:35.435 -> 
```

ESP8266 mam teraz w wersji 2.4.2.

**Comment by bfaliszek** [comment]
To jeszcze ostatnie pytanie. Na pewno masz wybraną płytkę NodeMCU 1.0? To chyba jeszcze ostatnia opcja jaka została. Jeśli tak, to chyba masz po prostu wadliwe BME280, które nie działa.

**Comment by opennas** [comment]
Włączona opcja NodeMCU 1.0 (ESP-12E Module) i dwa czujniki BME280. Jeszcze mam trzeci, ale muszę wlutować piny.
Mam dwa pełne zestawy Smogomierza i testowałęm na dwóch płytkach NodeMCU.

Zauważyłem teraz po zmianach, że mam w trakcie kompilacji błędy dotyczące biblioteki Wire. 
Nie mogę ich skopiować i proaszę o pomoc jak skopiować błędy z kompilacji.
Mam kompilacja zakończona, ale były błedy Wire.
Pewnie to pomoże ustalić przyczyny ...

**Comment by opennas** [comment]
Jeszcze dwie kwestie do upewnienia się:

1. Kabel USB mam podłączony do komputera z jednej a do NodeMCU z drugiej.
Po zaprogramowaniu mogę oglądać monitor portu szeregowego, ale nie mam podłączonego zasilania Smogomierza w dedykowanym konektorze. Może muszę dodatkowo podłączyć zasilania i wtedy dopiero pojawi się zasilanie i będzie działać I2C?

2. Po przeprogramowaniu straciłem urządzenie na WiFi i pomimo ponownego programowanie nie generuje sie sieć Smogomierz..
Jak zresetować WiFi w smogomierzu, abym po zaprogramowaniu mógł zmienić jemu sieć WiFi

3 Czy może lepiej jest ustawićdomyślną sieć w kodzie i podać nazwę SSID oraz hasło do przyłaczenia sieci jako default

**Comment by bfaliszek** [comment]
> masz po prostu wadliwe BME280, które nie działa.
🤷🏻‍♂️

**Comment by opennas** [comment]
Próbowałem już dwa BME280. Dzisiaj doszła trzecia sztuka BM280. Zaraz ją przygotuje i podłączę.

**Comment by opennas** [comment]
Teraz podłączyłem 3 sztukę BME280 i to samo :(
Zakupiłem w Botland i teraz po sprawdzeniu 3 sztuju pozostaje mi nic innego jak napisać reklamacje.
Mało prawdopodobne, aby w trzech wysyłkach tylko BME280 było 3X wadliwe.

**Comment by opennas** [comment]
Sukces, po resecie NodeMCU oraz ustawieniu SSDI na sztywno.
Zadziałał BME280.

Ciągle zastanawiam się co było przyczyną tego.

{
  "device_name": "Smogomierz-C68890",
  "pm1": 19,
  "pm25": 31,
  "pm10": 37,
  "temperature": 23.3,
  "pressure": 1022,
  "humidity": 25,
  "dewpoint": 8.306054
}
