### ISSUE TITLE
Jak zresetować sieć WiFi

### ISSUE THREAD

**Issue by opennas** [hackerspace-silesia/Smogomierz#19]
Po przeprogramowaniu straciłem urządzenie na WiFi i pomimo ponownego programowania nie generuje się sieć Smogomierz. 

Proszę o pomoc jak zresetować WiFi w smogomierzu, abym po zaprogramowaniu mógł zmienić jemu sieć WiFi.

Może jest opcja aby jednak ustawić domyślną sieć w kodzie i podać nazwę SSID oraz hasło do przyłaczenia sieci jako default.

**Comment by bfaliszek** [comment]
W karcie Konfiguracji jest przycisk, do kasowaniu ustawień WiFi.

**Comment by opennas** [comment]
Nie mogę tego znaleść w karcie konfiguracji.
Trzeba robić zworkę jakąśna zasilanym NodeMCU czy wystarczy przycisk
RST

lub

LASH

**Comment by opennas** [comment]
Zresetowałem programem oddzielnym i ustawiłem docelowe :)
Sukces.

**Comment by bfaliszek** [comment]
Zupełnie nie wiem o czym piszesz.
![konfig](https://user-images.githubusercontent.com/1752244/52527720-a8989300-2ccd-11e9-926b-7231ad84b8ba.jpg)

**Comment by eReS72** [comment]
> Zresetowałem programem oddzielnym i ustawiłem docelowe :) Sukces.

jakim programem resetowałeś?
