### ISSUE TITLE
Oprogramowanie Smogomierza które?

### ISSUE THREAD

**Issue by mickelk** [hackerspace-silesia/Smogomierz#20]
Hej! Pytanie może głupie ale nie mogę znaleść, są różne wersje aktualnego oprogramowania do smogomierza. Czym one się różnią?

Smogomierz_2.4.9_HPMA11550_build_19.05_3.01.2019.bin
Smogomierz_2.4.9_PMS-SparkFunBME280_build_19.05_3.01.2019.bin
Smogomierz_2.4.9_PMS_build_19.05_3.01.2019.bin
Smogomierz_2.4.9_SDS011_build_19.05_3.01.2019.bin

**Comment by bfaliszek** [comment]
W każdym z nich obsługiwany jest inny miernik pyłu zawieszonego w powietrzu PM2.5/PM10. W zależności od tego jakiego miernika użyjesz (PMS5003/7003, SDS011 lub HPMA11550) takie oprogramowanie wgrywasz. W przypadku PMSów jest jeszcze do wyboru opcja SparkFunBME280, gdzie działa BME280(temp/wilgotność/ciśnienie) od SparkFun. W "zwykłym"(bez SparkFunBME280) wspierane są wszystkie pozostałe wersje BME280.
