### ISSUE TITLE
Mikro krople i kryształki lodu przy ujemnych temperaturach

### ISSUE THREAD

**Issue by Keyoo77** [hackerspace-silesia/Smogomierz#22]
Witam 
Czy zestaw kompensuje wpływ mikro kropel wody i kryształków lodu występujących w powietrzu przy ujemnych temperaturach?

**Comment by bfaliszek** [comment]
Tak. Smogomierz domyślnie bierze pod uwagę wilgotność powietrza i koryguje pomiary PM2.5/PM10. Jeśli ktoś nie chce z tego korzystać, to można wyłączyć automatyczną korekcję w ustawieniach.
