### ISSUE TITLE
Sensirion SPS30

### ISSUE THREAD

**Issue by CapanoThomas** [hackerspace-silesia/Smogomierz#26]
Cześć

wpadł mi w ręce czujnik PM2.5 PM4 i PM10 Sesiriona SPS30, czy istnieje opcja, żeby go jakoś podłączyć do naszego Smogomierza?

**Comment by bfaliszek** [comment]
Bardzo fajny miernik. Polecam 😁

![sensirionsps30](https://user-images.githubusercontent.com/1752244/53748674-176ca480-3ea6-11e9-87f5-b31e1918373d.jpeg)

Co do wsparcia w Smogomierzu to pewnie dodam w przyszłości, ale raczej wątpię, żeby wiele osób go użyło w tym projekcie. SPS30 kosztuje jakieś 160 zł. Za tyle można mieć pełen komplet części na Smogomierz.

**Comment by CapanoThomas** [comment]
HEHE, o proszę, a masz może do niego jakiś fragment kodu/szkic pod arduino i NodeMCU żeby zrzucał dane do Gafany? Przyznam, że potrzebuję pomocy w tym temacie.

**Comment by bfaliszek** [comment]
@CapanoThomas Mam kod dla ESP32. Nie sprawdzałem czy działa z ESP8266. https://github.com/bfaliszek/SensirionSPS30_InfluxDB

**Comment by CapanoThomas** [comment]
@bfaliszek dzięki wielkie, czekam na wtyczkę jeszcze i będę testował. 
BTW, na firmę ten czujnik kosztuje 114zł w SOS, a jak rozumiem wygrywa żywotnością i dokładnością pomiarów.
