### ISSUE TITLE
Panel logowania

### ISSUE THREAD

**Issue by krupniok200** [hackerspace-silesia/Smogomierz#28]
Przydałoby się jakieś zabezpieczenie zakładki konfiguracji oraz aktualizacji. Teraz nawet w sieci lokalnej trochę mieszane uczucia czy ktoś ci na palę nie pozmienia konfiguracji a co dopiero po przekierowaniu portów z zewnątrz.

**Comment by bfaliszek** [comment]
Będzie w 2.5.1 😉
