### ISSUE TITLE
Możliwość zmiany I2C na dowolne piny

### ISSUE THREAD

**Issue by kuba-str** [hackerspace-silesia/Smogomierz#29]
mam propozycję, jak pisałem wcześniej moja płytka ma magistralę I2C tylko na pinach 0,2. Ty zaś domyślnie używasz go na 5,4. Nie mogę przez to, aktualizować płytki plikiem bin tylko muszę to robić ręcznie kompilować co powoduje problemy wiadomego typu :) czy mógłbyś dodać możliwość skonfigurowania pinów na jakich używane są czujniki ?

**Comment by bfaliszek** [comment]
Dodane w branchu DEV
