### ISSUE TITLE
Wyliczanie punktu rosy

### ISSUE THREAD

**Issue by skwaruch** [hackerspace-silesia/Smogomierz#30]
Jakie jest źródło wzoru wyliczającego punkt rosy w "smogomierz"?
(BMESensor.temperature - ((100 - BMESensor.humidity) / 5));
Ten wzór odpowiada za wyliczanie punktu rosy?

**Comment by bfaliszek** [comment]
Tak, to uproszczony wzór do obliczania punku rosy: https://en.wikipedia.org/wiki/Dew_point#Simple_approximation
Nic nie stoi na przeszkodzie, żeby wprowadzić bardziej złożone.

**Comment by skwaruch** [comment]
Powiedział bym bardzo bardzo uproszczony.
Dodajcie taki:
dewPoint = pow(BMESensor.humidity/100, 0.125)*(112+0.9*BMESensor.temperature)+0.1*BMESensor.temperature-112;

**Comment by bfaliszek** [comment]
OK, poprawiłem sobie w kodzie. Punkt rosy, według podanego wzoru będzie obliczany w wersji oprogramowania 2.5.1.

**Comment by skwaruch** [comment]
Fajnie. 
Czy chcecie bym napisał co jeszcze pozmieniałem?

**Comment by bfaliszek** [comment]
Jasne. W 2.5.1 dodałem możliwość ustawienia loginu i hasła dla stron z konfiguracją oraz update. Dodałem też obsługę MQTT(ale nie testowałem jeszcze czy działa). Planuję też podzielić plik webserver.h na mniejsze pliki. Ułatwi to tłumaczenie interfejsu oraz umożliwi dodanie różnych skórek dla panelu użytkownika.
