### ISSUE TITLE
Brak wykresów

### ISSUE THREAD

**Issue by ookris** [hackerspace-silesia/Smogomierz#32]
Po aktualizacji do najnowszej wersji wykresy se strony z pomiarami nie wyświetlają się. 

Nie można połączyć się z serwerem 
http://metrics.airmonitor.pl:3000/dashboard-solo/db/airmonitor?orgId=1&var-latitude=51.261898&var-longitude=15.580199&refresh=1m&panelId=14

**Comment by bfaliszek** [comment]
Airmonitor ma od wczoraj problemy. Zupełnie nie działa http://metrics.airmonitor.pl:3000 
Gdy zacznie działać to pojawią się wykresy, bo stamtąd są pobierane.

**Comment by bfaliszek** [comment]
Problem leżał po stronie Airmonitora. Teraz już wykresy działają. Źle wyświetla tylko wykres z ThingSpeak dla PM2.5, ale w 2.6.1 to poprawię.
