### ISSUE TITLE
changing chipID may cause collision with other sensors on Luftdaten.info

### ISSUE THREAD

**Issue by ricki-z** [hackerspace-silesia/Smogomierz#35]
At the moment Luftdaten.info doesn't accept regsitrations for devices with this firmware.
The possibility to change the chipID may lead to collisions with other sensors (not only for Luftdaten.info).
Please contact me for more infos (we had a collsion with the third registration of such a device).
You could change the device prefix in "X-Sensor" (src/luftdaten.cpp) from esp8266 to smogomierz . Users then need to send "smogomierz-"+chipID as the chipID at registration. So collisions may only affect users of this firmware.

**Comment by bfaliszek** [comment]
thanks for the information. I will correct the code as suggested. I will change the X-Sensor to a smogomierz

**Comment by bfaliszek** [comment]
1) Removed change ChipID option: https://github.com/hackerspace-silesia/Smogomierz/commit/173f307d755490a2c5fe84594a6c6be9225e7a8c
2) Added "smogomierz" to X-Sensor: https://github.com/hackerspace-silesia/Smogomierz/commit/838135d37aec250721df52e6304eeee744c49d56

**Comment by ricki-z** [comment]
could you please also add the prefix to the config page so that user will see what "chipID" they have to use for registration?

**Comment by bfaliszek** [comment]
Yes. I also added it to the configuration page https://github.com/hackerspace-silesia/Smogomierz/commit/173f307d755490a2c5fe84594a6c6be9225e7a8c#diff-8f8f75b09c165f6369f2f745e4b7ccefR388

<img width="642" alt="Zrzut ekranu 2019-03-27 o 20 34 43" src="https://user-images.githubusercontent.com/1752244/55106643-c419fa80-50cf-11e9-8a8e-bd58a655a24f.png">

**Comment by ricki-z** [comment]
Then I can close this issue.
