### ISSUE TITLE
2.6.0 brak pm1 i 2.5 z thingspeak

### ISSUE THREAD

**Issue by skubi23t** [hackerspace-silesia/Smogomierz#36]
Hej
Zaktualizowałem właśnie soft do 2.6.0 i zamiast wyników pm1 i 2.5 to mam wrzucony jeszcze raz smogomierz jak na zdjeciu nizej:

https://i.imgur.com/Hn5k4Np.png

Resetowałem ustawienia do fabrycznych i próbowałem w trybie incognito. Nie pomaga.

**Comment by bfaliszek** [comment]
Poprawione w 2.6.1, które wjechało dosłownie 2 minuty temu

**Comment by bfaliszek** [comment]
https://github.com/hackerspace-silesia/Smogomierz/blob/master/firmware/prerelease_Smogomierz_2.6.1_PMS_build_27.03.2019.bin

**Comment by skubi23t** [comment]
Potwierdzam działa.
