### ISSUE TITLE
OTA zepsuł AirMonitor - niewidoczna lokacja

### ISSUE THREAD

**Issue by Marszczak** [hackerspace-silesia/Smogomierz#52]
Po ostatni OTA moj Smogomierz zniknął z AirMonitora, wiem ze jakies opóźnienie jest dopuszczalne, ale minęły 2 doby i śladu na mapie nie ma.
Czekać cieprliwie?

**Comment by bfaliszek** [comment]
Przywróć ustawienia domyślne w Konfiguracji Smogomierza i wpisz jeszcze raz współrzędne. Jeśli to nic nie da, zarejestruj jeszcze raz urządzenie w AirMonitora.

**Comment by Marszczak** [comment]
Po przywróceniu domyślnych ze strony pomiary zniknęły pomiary. Zostały tylko wykresy. 

Dziękuje - Marcin

**Comment by Marszczak** [comment]
Przed przywróceniem ustawień 



Po resecie 



—
Dziękuje
Marcin

**Comment by Marszczak** [comment]
![IMG_1487](https://user-images.githubusercontent.com/35682921/66326051-9f2cfc80-e928-11e9-991c-87732885f624.png)
![IMG_1488](https://user-images.githubusercontent.com/35682921/66326062-a3f1b080-e928-11e9-97e6-7d39cdd503f2.png)

**Comment by bfaliszek** [comment]
@Marszczak Przywrócenie ustawień domyślnych coś dało, czy nadal nie działa?

**Comment by kkszysiu** [comment]
Dzisiaj zgłosiłem do AirMonitora, że wersja 2.7.2 poprawia współrzędne - zmienili oni wiadomość która była wysyłana przy rejestracji (wcześniej przy wysyłaniu Google Formsów wysyłali wiadomość o błędnych współrzędnych).

**Comment by bfaliszek** [comment]
Przywrócenie ustawień domyślnych w Konfiguracji i ponowne wpisanie swoich współrzędnych załatwia sprawę.
