### ISSUE TITLE
Wersja 2.7.2 zepsuła wtyczkę do homebridga

### ISSUE THREAD

**Issue by Marszczak** [hackerspace-silesia/Smogomierz#53]
Homebridge się wysypuje na 2.7.2 
![IMG_0307](https://user-images.githubusercontent.com/35682921/66328034-2f207580-e92c-11e9-93a2-e090fc7fe294.png)

**Comment by bfaliszek** [comment]
Wydaje mi się, że to raczej problem samej wtyczki a nie Smogomierza. 2.7.2 nie zmienia sposobu wyświetlania info na podstronie /api, a tylko ona jest wykorzystywana przez homebridge. W wolnej chwili sprawdzę czy u mnie homebridge działa poprawnie

**Comment by Marszczak** [comment]
Cofnąłem się do 2.7.1 i ruszyło z kopyta.
