### ISSUE TITLE
Problemy z czujnikiem PM7003

### ISSUE THREAD

**Issue by kkszysiu** [hackerspace-silesia/Smogomierz#57]
Witam.

Wydaje mi się, że mam jakieś problemy z moim czujnikiem albo integracją z nim.
Otóż raz na jakieś 24 godziny czujnik zaczyna wysyłać wartości -1.

<img width="416" alt="Screenshot 2019-10-17 at 14 53 35" src="https://user-images.githubusercontent.com/70684/67011194-6abafc80-f0ef-11e9-968c-f69c91a91be8.png">
<img width="501" alt="Screenshot 2019-10-17 at 14 59 38" src="https://user-images.githubusercontent.com/70684/67011199-6d1d5680-f0ef-11e9-80f3-7c2f3f3a3100.png">

Występowanie wygląda zupełnie losowo. Mogę spokojnie podpiąć się do interfejsu WWW ale i tam widzę jedynie wartości -1.
~~Jedyne co wtedy pomaga to reset smogomierza.~~
A jednak nie. Nie ruszyłem smogomierza tym razem, po prostu wszedłem na stronę smogomierza i pomimo tego, że widziałem na początku wartości -1 to po 3 minutach czujnik się obudził i zaczął pokazywać dobre wartości. Hmm

Spotkał się ktoś wcześniej z takim problemem?

**Comment by bfaliszek** [comment]
Sprawdź czy kabelki są mocno dociśnięte. Wydaje mi się, że to może być problem z podłączeniem.

**Comment by kkszysiu** [comment]
@bfaliszek, z kabelkami wszystko wydaje się być ok. Dodałem restart esp co godzinę i wygląda to teraz czasami tak:
<img width="395" alt="Screenshot 2019-10-21 at 16 19 40" src="https://user-images.githubusercontent.com/70684/67213773-e7671700-f41e-11e9-8985-877f7ad5cea4.png">

Więc nadal od czasu do czasu problem występuje ale restart pomaga.

Ciekawe czy to może być jakoś związane z tym, że używam ESP32. Testowałeś może Smogomierz na ESP32?

**Comment by bfaliszek** [comment]
Mam jeden na ESP32, ale nie używam go na co dzień, więc ciężko mi powiedzieć jak to wygląda na dłuższą metę. Jutro go gdzieś podepnę i zobaczę jak będzie działał.

**Comment by kkszysiu** [comment]
Dzięki @bfaliszek. Póki co dodałem restart jeśli pomiary wszystkich PM miały wynik -1.
W takim przypadku dumpuje też wszystkie pomiary etc. i wysyłam sobie to do mojego lokalnego serwera. 

Może uda mi się ustalić co jest nie tak. Przez ostatnie 24 godziny jednak problem nie wystąpił.

**Comment by bfaliszek** [comment]
a tak z ciekawości, jak masz ustawioną częstotliwość wykonywania pomiarów? Oraz ile robisz pomiarów do uśrednień?

**Comment by kkszysiu** [comment]
@bfaliszek, tutaj:
<img width="1083" alt="Screenshot 2019-10-22 at 19 30 59" src="https://user-images.githubusercontent.com/70684/67312980-8153c000-f502-11e9-8b56-cb849ded1ede.png">
