### ISSUE TITLE
Zawieszanie SDS011

### ISSUE THREAD

**Issue by skwaruch** [hackerspace-silesia/Smogomierz#59]
Coś nie ma szczęścia do czujników PMS7003 nie wyłącza się softwear'owo a SDS011 wiesza mi się średnio co dzień (smogomierz pokasuje ciągle tą samą wartość). Ponowne uruchomienie czujnika pomaga.

**Comment by bfaliszek** [comment]
Oprogramowanie 2.7.2 i ESP8266?

**Comment by skwaruch** [comment]
Tak

**Comment by piotrrekkk** [comment]
Jakaś aktualizacja odnośnie tego buga? Też się z nim spotkałem.

**Comment by Kriztower** [comment]
![Screenshot_20200207-133101](https://user-images.githubusercontent.com/60783808/74034316-52316380-49b8-11ea-87b6-c1c79fc9e768.png)
U mnie podobnie. Wiesza się minimum codziennie, jak nie kilka razy dziennie. Po restarcie kilka godzin spokoju i znowu.

**Comment by slawek0200** [comment]
Ja również potwierdzam, restart co kilka godzin. SDS011 się zawiesza.

**Comment by theundefined** [comment]
U mnie na wemos d1 + sds11 +dht22 działa stabilnie. 2.7.2.
Jedno co to mam wrażenie że zaniża wielkości pomiarów - trend jest zgodny z tym co okoliczne czujniki syngeos i looko2, ale wielkosci niższe.

**Comment by slawek0200** [comment]
U mnie płytka CH340 NodeMcu V3, +SDS011 +BME280 są problemy z zawieszaniem. Wymienię na  płytkę WEMOS D1 i sprawdzę.

**Comment by bfaliszek** [comment]
> U mnie na wemos d1 + sds11 +dht22 działa stabilnie. 2.7.2.
> Jedno co to mam wrażenie że zaniża wielkości pomiarów - trend jest zgodny z tym co okoliczne czujniki syngeos i looko2, ale wielkosci niższe.

Ogólnie looko2 używa mierników PMS5003. Najbardziej zauważalna różnica pomiędzy PMS a SDS to różnica w wykrywaniu poziomu zanieczyszczeń przy ich niskim poziomie. SDS lepiej wykrywa poziomy do około 15ug/m3. PMSy zazwyczaj pokazują 0-2, 5 albo od razu 10ug/m3. SDS jest po prostu bardziej czuły przy niskich stężeniach pyłu. To może być powodem rozbieżności. Plus dht22 często podaje wilgotność z czapy, więc może też wpływać na pomiary PM, jeśli masz włączoną kalibrację w ustawieniach.

**Comment by bfaliszek** [comment]
> U mnie płytka CH340 NodeMcu V3, +SDS011 +BME280 są problemy z zawieszaniem. Wymienię na płytkę WEMOS D1 i sprawdzę.

Wydaje mi się, że zmiana z NodeMcu na Wemosa nie powinna mieć żadnego wpływu. Sprawdzę w wolnej chwili jak całość działa z SDSem. Możliwe, że jest jakiś błąd w bibliotece do obsługi SDSów, bo ten błąd nie występuje w innych wersjach oprogramowania, a one różnią się tylko obsługiwanymi miernikami pyłu.

**Comment by Kriztower** [comment]
> > U mnie na wemos d1 + sds11 +dht22 działa stabilnie. 2.7.2.
> > Jedno co to mam wrażenie że zaniża wielkości pomiarów - trend jest zgodny z tym co okoliczne czujniki syngeos i looko2, ale wielkosci niższe.
> 
> Ogólnie looko2 używa mierników PMS5003. Najbardziej zauważalna różnica pomiędzy PMS a SDS to różnica w wykrywaniu poziomu zanieczyszczeń przy ich niskim poziomie. SDS lepiej wykrywa poziomy do około 15ug/m3. PMSy zazwyczaj pokazują 0-2, 5 albo od razu 10ug/m3. SDS jest po prostu bardziej czuły przy niskich stężeniach pyłu. To może być powodem rozbieżności. Plus dht22 często podaje wilgotność z czapy, więc może też wpływać na pomiary PM, jeśli masz włączoną kalibrację w ustawieniach.

Jeszcze się u mnie na zewnątrz nie zdąży o żeby czujnik (sds011) pokazał <10 😀

**Comment by Kriztower** [comment]
Niestety znowu to samo😭
Widać dwa zawieszenia, a po restarcie znowu mierzy przez kilka godzin i znowu zawias. 
A ciekawe że temperaturę i wilgotność pokazuje dobrze cały czas. 
![Screenshot_20200210-151730](https://user-images.githubusercontent.com/60783808/74167479-9cb91700-4c28-11ea-9de8-fb5e468e33bb.png)
![Screenshot_20200210-151750](https://user-images.githubusercontent.com/60783808/74167497-a3e02500-4c28-11ea-8219-112e1fab56aa.png)
![Screenshot_20200210-151757](https://user-images.githubusercontent.com/60783808/74167522-ab073300-4c28-11ea-80b7-aa01ed3c8270.png)
![Screenshot_20200210-151809](https://user-images.githubusercontent.com/60783808/74167587-c2462080-4c28-11ea-8ef7-9134a70c3a2e.png)
![Screenshot_20200210-151822](https://user-images.githubusercontent.com/60783808/74167608-c8d49800-4c28-11ea-8059-38c9af2026f0.png)
![Screenshot_20200210-151855](https://user-images.githubusercontent.com/60783808/74167733-f02b6500-4c28-11ea-9fc0-0bb3ecb49baf.png)
![Screenshot_20200210-151923](https://user-images.githubusercontent.com/60783808/74167742-f7eb0980-4c28-11ea-83b5-a255b43dd2fc.png)
![Screenshot_20200210-171708](https://user-images.githubusercontent.com/60783808/74167868-34b70080-4c29-11ea-8557-2f2cc23b0ed5.png)

**Comment by skwaruch** [comment]
Nic w tym ciekawego że jest temp. bo zawiesza się SDS011, który temp. nie mierzy.

**Comment by theundefined** [comment]
Może inny zasilacz?

**Comment by Kriztower** [comment]
> Może inny zasilacz?

Chodzi bezpośrednio z płytki. 



> Nic w tym ciekawego że jest temp. bo zawiesza się SDS011, który temp. nie mierzy.

No tak tylko dlaczego? Wina czujnika? Przecież po restarcie działa ok.

**Comment by theundefined** [comment]
Może zwiesza się SDS przy problemach z zasilaniem? Strzelam. Jak nie masz jak zmienić SDS spróbuj jakiś mocniejszy zasilacz użyć :-)

**Comment by bfaliszek** [comment]
@Kriztower tutaj opcje są dwie, a w zasadzie to trzy. Dane o temperaturze są wysyłane, więc urządzenia działa. Pomiary temperaturze są dobrze wykonywane, więc jedyne co nie działa to wykonywanie pomiarów przez SDS. Stąd trzy opcje:

+ biblioteka do obsługi SDS ma jakieś błędy i co jakiś czas nie działa

+ trzeba wymienić kabelki do SDS, bo nie można się z nim czasami połączyć

+ jest problem z zasilaniem, lub sam SDS jest wadliwy

**Comment by skwaruch** [comment]
Zmieniłem wczoraj zasilacz na mocniejszy i o ciut większym na napięciu (5,12V wcześniej 4,9..V).
Też się zawiesiło :( .

**Comment by Kriztower** [comment]
U mnie cały czas się zawiesza. Raz chodzi pół dnia raz półtora dnia, ale zawsze się zawiesi. Czy dałoby radę dopisać linijkę żeby np. co 10 min nastąpił restart samego czujnika, poprzez odłączenie do niego zasilania? 

![Screenshot_20200221-123026](https://user-images.githubusercontent.com/60783808/75052512-03afb900-54d0-11ea-8434-9dd333986b6b.png)

**Comment by MiG-41** [comment]
U mnie jeszcze inna reakcja , na wsadzie ESP8266_Smogomierz_2.7.2_SDS011_build_4.10.2019.bin działał 5 dni i było ok , zaktualizowałem automatycznie do najnowszej 2.7.9 SDS i wtedy zaczęły się zawieszania czytnika. Zwykły restart nie wystarczał , trzeba było odłączać na chwilę zasilanie.
Teraz wgrałem ESP8266_Smogomierz_2.7.3_SDS011_build_17.01.2020.bin , na razie od 12godzin jest ok ( choć tu mam wielkie problemy z ustawieniem konfiga , uruchamiam jedno , i przestawia się do defaultowych ustawien , czasami cos przestawie , a np jezyk sie cofa na angielski..)
