### ISSUE TITLE
Link do elementu do wydruku 3D

### ISSUE THREAD

**Issue by jozwikp** [hackerspace-silesia/Smogomierz#6]
Nie działa
https://github.com/hackerspace-silesia/Smogomierz/blob/master/80x80x40mm.stl

Źródło 
https://github.com/hackerspace-silesia/Smogomierz/blob/master/instrukcje/components.md

**Comment by bfaliszek** [comment]
Poprawny link to https://github.com/hackerspace-silesia/Smogomierz/blob/master/instrukcje/80x80x40mm.stl
