### ISSUE TITLE
Po podłączeniu do zasilania PMS7003 działa bez przerwy do czasu kolejnego interwału

### ISSUE THREAD

**Issue by surmacz** [hackerspace-silesia/Smogomierz#61]
Jeśli mam pomiary robione co 15 minut, to przez pierwsze 15 minut po podłączeniu do prądu nie ma pomiaru, ale czujnik cały czas chodzi. Tak musi być?

**Comment by bfaliszek** [comment]
A jak masz ustawioną opcję "Ciągłe pomiary PM"? Jeśli jest włączona, to miernik chodzi ciągle, jeśli jest wyłączona, to jest usypiany pomiędzy seriami pomiarów.

**Comment by surmacz** [comment]
Ciągle pomiary: NIE
Po pierwszych 15 min. działa OK i się wyłącza, tylko te pierwsze 15 minut ciągle mieli.

**Comment by surmacz** [comment]
To nie przypadkiem tutaj jest ustawione?:
https://github.com/hackerspace-silesia/Smogomierz/blob/v2.7.3/Smogomierz.ino#L423
`pms.sleep()` jest dopiero robione po pierwszym pomiarze.

**Comment by bfaliszek** [comment]
`if (FREQUENTMEASUREMENT == true) {
      pms.wakeUp();
      delay(500);
      pms.activeMode();
    } else {
      pms.passiveMode();
      delay(500);
      pms.sleep();
    }`

ten `pms.wakeUp();` jest robiony tylko jeśli masz włączone ciągłe pomiary(FREQUENTMEASUREMENT), jeśli są wyłączone, to wykonywany jest kod poniżej linijki `    } else {`
