### ISSUE TITLE
poziom stężenia pyłów --- > poziom jakości powietrza

### ISSUE THREAD

**Issue by ppuz** [hackerspace-silesia/Smogomierz#62]
zauważyłem rozbieżność pomiędzy poziomem stężenia pyłów wskazywanymi przez Smogomierz, a wyświetlanym poziomem jakości powietrza. W porównaniu ze skalą innej aplikacji.

Czy te poziomy ustalone są na sztywno ?

![IMG_1416](https://user-images.githubusercontent.com/37309906/68842543-d1b7db00-06c6-11ea-99e9-8aec7a729b00.png)
![IMG_1417](https://user-images.githubusercontent.com/37309906/68842544-d1b7db00-06c6-11ea-9c63-83232eff90ca.png)

**Comment by bfaliszek** [comment]
Wtyczka dla Homebridge ma ustalone progi na podstawie europejskich norm jakości powietrza. Dokładnie takich samych jak na mapie http://www.eea.europa.eu/themes/air/air-quality-index
Poniżej jest też fragment kodu wtyczki, który to interpretuje. 
https://github.com/bfaliszek/homebridge-smogomierz/blob/446a7b805683d77ef0fb49cfc645437ea4cdebb9/index.js#L284-L301

Jeśli chodzi o Airly, to używają chyba polskiego Indeksu jakości powietrza albo czegoś bardzo zbliżonego do niego.
http://powietrze.katowice.wios.gov.pl/indeks-jakosci-powietrza
