### ISSUE TITLE
wtyczka homebridge ---> brak ujemnych temp.

### ISSUE THREAD

**Issue by ppuz** [hackerspace-silesia/Smogomierz#65]
jak na załączonych screenach.
Na stronie -1.9, a w aplikacji 0.
![IMG_1471](https://user-images.githubusercontent.com/37309906/70301594-1254d100-17fb-11ea-98b9-37e976f05214.jpg)
![IMG_1472](https://user-images.githubusercontent.com/37309906/70301595-1254d100-17fb-11ea-9328-583eadc1bc89.PNG)

**Comment by bfaliszek** [comment]
To kwestia wtyczki, a nie samego Smmogomierza, więc lepiej to umieścić w repozytorium wtyczki: https://github.com/bfaliszek/homebridge-smogomierz
