### ISSUE TITLE
Stabilność sprzętu - zawieszony smogomierz

### ISSUE THREAD

**Issue by jozwikp** [hackerspace-silesia/Smogomierz#7]
Cześć

Zauważyłem problem ze smogomierzem. Zawiesza się. Rzadko udaje mi się utrzymać go więcej niż dobę w działaniu. Czy ktoś spotkał podobne problemy? Może dobrze byłoby go softem restartować raz na jakiś czas?

**Comment by ziyo98** [comment]
Hej,  miałem to samo - pomogła wymiana zasilacza na mocniejszy

**Comment by bfaliszek** [comment]
@jozwikp Mam kilka mierników i w żadnym nie mam problemu z wieszaniem się. W jednym czasami przestaje na godzinę lub dwie działać bme280 i podejrzewam, że to kwestia zasilania. Jakich zasilaczy używasz? 
BTW W oprogramowaniu jest systemowy reset ustawiony na 24 godziny ;)

**Comment by jozwikp** [comment]
ja mam 5V - 2500mA - za mało?

**Comment by bfaliszek** [comment]
2,5A na pewno wystarczy, na 500mA działa bez problemu. Co rozumiesz przez "Zawiesza się"? Nie działa interface www czy nie wysyła danych do zewnętrznych serwisów? Od ponad roku wysyłam pomiary do InfluxDB z kilku Smogomierzy i poza sporadycznymi zawieszeniami się BME280 reszta pomiarów działa bez problemów. 
Możesz też spróbować podłączyć kabel usb bezpośrednio do ESP i włączyć w konfiguracji debug. W monitorze portu szeregowego powinny być komunikaty o każdym pomiarze i ewentualnych błędach.

**Comment by jozwikp** [comment]
Nie działa endpoint /api i interfejs www
rusza po restarcie prądowym.

**Comment by jozwikp** [comment]
Wersja oprogramowania: 2.4.7 build 13:05_18.12.2018
