### ISSUE TITLE
Wyświetlanie wykresów z serwisu AirMonitor - resetują się ustawienia thingspeaka

### ISSUE THREAD

**Issue by XsPolar** [hackerspace-silesia/Smogomierz#70]
Po zmianie parametru Wyświetlanie wykresów z serwisu AirMonitor: NIE  - resetują się ustawienia thingspeaka, wysokość i ustawienia dla luftdaten.

**Comment by bfaliszek** [comment]
Jaka wersja oprogramowania? 2.7.2? Smogomierz z ESP8266 i PMS7003? Właśnie sprawdziłem na takim u siebie i wszystko zadziałało. Wyłączenie wykresów AirMonitora, nie wpłynęło na ustawienia Thingspeaka. 

Jedyne co przychodzi mi na myśl, to opcja z błędnym wczytaniem strony z konfiguracją. Jeśli na dole są teksty w "{}" i brakuje tłumaczeń, to przy zapisaniu, czasami przywraca ustawienia domyślne. Spowodowane jest to brakami pamięci w ESP8266. Tylko to dzieje się niezależnie od tego jakie zmieni się ustawienia. Jeśli jest za mało pamięci, to się nie zapiszą i dla bezpieczeństwa przywracane są te domyślne.

**Comment by XsPolar** [comment]
Wersja 2.7.2 Chyba masz rację z tym brakiem pamięci, bo jest problem czasem reloadem strony konfiguracji po zapisaniu zmian. Ale tylko po zmianie tego parametru resetuje mi ustawienia. Pozostałe zmiany nie czyszczą danych do thinspeaka.

**Comment by skubi23t** [comment]
U mnie też nie zawsze chce się wczytać strona konfiguracji tylko wyskakuję zmienne. Pewnie to ten brak pamięci..

**Comment by bfaliszek** [comment]
Jeśli macie chwilę, to możecie przetestować prerelease 2.7.4(ESP8266 z PMSx003). Podzieliłem stronę Config na dwie mniejsze. Powinny się poprawnie wczytywać i dzięki temu nie powinno być już problemów ze znikaniem ustawień. https://github.com/hackerspace-silesia/Smogomierz/blob/dev/firmware/ESP8266/prerelease_ESP8266_Smogomierz_2.7.4_PMS_build_23.01.2020.bin

**Comment by skubi23t** [comment]
Jest lepiej, ale i tak potrafi zrobić psikusa
![Screenshot_20200124-071542](https://user-images.githubusercontent.com/57182727/73048433-6a15cd00-3e79-11ea-8b64-954a4465b549.jpg)

**Comment by diggahpl** [comment]
prerelease_ESP8266_Smogomierz_2.7.4_PMS_build_2.02.2020 - poprawiło wprowadzanie konfiguracji. Nie zaobserwowałem już pojawiania się {}.

**Comment by skubi23t** [comment]
Fakt. U mnie to pojawiło się tylko raz niedługo po wygraniu.

**Comment by bfaliszek** [comment]
W prerelease z lutego mocno zwiększyłem ilość pamięci przeznaczonej na config. O prawie 1/2. W dodatku zoptymalizowałem użycie pamięci, więc powinno być lepiej jeśli chodzi o problemy z {} czy znikającymi danymi z konfiguracji. Przypuszczam, że to było problemem przy wyświetlaniu wykresów z AirMonitor.

**Comment by bfaliszek** [comment]
https://github.com/hackerspace-silesia/Smogomierz/releases/tag/v2.7.5
