### ISSUE TITLE
Wilgotność powietrza a wyniki pomiarów

### ISSUE THREAD

**Issue by jakubcichocki** [hackerspace-silesia/Smogomierz#71]
Witam,

jak wiadomo wilgotność powyżej 60-70% znacząco wpływa na wyniki pomiarów. Widziałem na twitterze, że były jakieś próby zaadoptowania grzałki. Na czym stanął temat, czy można jakoś pomóc w jego rozwoju?

**Comment by bfaliszek** [comment]
Na chwilę obecną jest tylko kalibracja w oprogramowaniu: https://github.com/hackerspace-silesia/Smogomierz/blob/master/Smogomierz.ino#L980
Jeśli chodzi o grzałkę, to sprawdziłem kilka różnych modeli i ich zachowanie w niskich temperaturach(-25C). 

Znalazłem ogólnie 3 modele grzałek na 12V. Takie z max temp. 80-120-220C.
Sprawdziłem jak spisują się przy nagrzewaniu powietrza. Powietrze było zaciągane przez wiatraczek z SDS011. Pomiary robiłem w zamrażalniku. Całość na starcie miała -25C. Pomiary temperatury zapisywałem co kilkanaście minut, aby na koniec porównać, jak te grzałki radzą sobie z ogrzewaniem takiego powietrza.

Docelowo mierniki pyłu PM10/PM2.5 najlepiej pracują z powietrzem o temperaturze +25C. Chciałbym używać grzałki zawsze gdy temperatura spadnie poniżej +20C, aby podgrzewać do około +30C. Utrzymywanie temperatury w tym zakresie(pomiędzy +20C i +30C) zagwarantuje nam optymalne warunki termiczne dla pomiarów oraz spowoduje usunięcie części wilgoci z powietrza. Dodatkowo wydłuży to też żywotność całego urządzenia.

**Grzałka 80C** - Przy ciągłej pracy nie była w stanie nagrzać powietrza o temperaturze -25C do wartości dodatnich. Udało się nagrzać do max -6,5C(30 minut po rozpoczęciu testu). Później temperatura się ustabilizowała na -7,5C(pomiar po 2 godzinach od rozpoczęcia nagrzewania).

**Grzałka 220C** - Drugi skrajny przypadek, czyli najmocniejsza grzałka z Aliexpressu. Tutaj po 10 minutach miałem już ponad +35C. Po 30 minutach temperatura powietrza wynosiła już +54C. Maksymalną temperaturę grzałka osiągnęła po 60 minutach ciągłej pracy i temperatura powietrza wynosiła wtedy +63C. Po dwóch godzinach pomiarów wartość ustabilizowała się na poziomie +60C. Przy tej grzałce pojawiło się kilka problemów. Pierwszym z nich była zbyt wysoka temperatura. Doprowadziła ona do tego, że wilgotność powietrza w czasie tych pomiarów zawsze pokazywała 0%(od +40C wilgotność zawsze wynosiła 0%). Kolejnym problemem był fakt, że użyłem plastikowej obudowy do zamocowania grzałki. Sama grzałka nagrzewała się tak mocno, że zaczęła topić obudowę i w efekcie musiałem poszukać alternatywy. Użyłem mosiężnych elementów(topią się dopiero powyżej +900C!). Wyniki pomiarów były prawie identyczne, tylko tym razem w zamrażalniku nie śmierdziało mi topionym plastikiem. 

**Grzałka 110C** - Mój faworyt. W przypadku tej temperatury nie ma możliwości stopienia plastikowej obudowy(ABS topi się w okolicy 210-220C). Po 10 minutach od włączenia grzałki, temperatura powietrza wynosiła już +18,6C(Wilgotność 20,7%). Po 2 godzinach temperatura ustabilizowała się na poziomie +60C. Maksymalne wartości w przypadku tej grzałki były bardzo zbliżone do tej najmocniejszej, z tą różnicą, że wersja Max 110C osiągała je później. Właśnie z tego powodu wydaje mi się najlepsza, bo będzie ją można najłatwiej kontrolować. No i nie stopi obudowy ;)

Na koniec sprawdziłem też jak szybko całość się schładza, po tym jak wyłączę grzałkę. Chociaż te pomiary robiłem tylko na metalowej obudowie, więc w przypadku plastiku nastąpi to znacznie szybciej. 

Temperatura z +60C po 10 minutach od wyłączenia grzałki spadła do +16,8C(wciąż 0% wilgotności). Dopiero po 20 minutach temperatura spadła poniżej zera. Wilgotność zaczęła się pojawiać przy temperaturze około +10C. 

**Skąd przyszliśmy? Kim jesteśmy? Dokąd idziemy?** 

Wiem z jakich elementów zrobić obudowę na grzałkę(plastikowe mufki i nyple 1" i 3/4"), wiem która grzałka byłaby optymalna(Tmax 110C). Pozostało przemyśleć sposób sterowania samą grzałką. Teoretycznie można użyć rozwiązania https://nettigo.pl/products/nettigo-air-monitor-heca-modul-kontroli-grzalki-ptc od niego zacząłem swoje pomiary i na nim bazowałem, tylko wydaje mi się, że da się to zrobić znacznie taniej. Bez konieczności kupowania dedykowanej płytki. Choć z drugiej strony warto przemyśleć użycie tego rozwiązania, bo mamy tutaj możliwość sterowania grzałką(musiałbym sprawdzić ich kod, jak to się robi) oraz wykonywanie pomiarów temperatury i wilgotności powietrza przed wprowadzeniem ich do samej obudowy Smogomierza. W zasadzie gdybyśmy chcieli kupić sobie miernik temp/humi oraz przekaźnik do sterowania zasilaniem grzałki, to wydalibyśmy u Chińczyków pewnie połowę tej ceny. To jest do przemyślenia. 

Kod, kod, kod, tutaj trzeba dopisać sposób sterowania grzałką. Chciałbym ją uruchamiać, gdy temp spadnie <+20C i wyłączyć, gdy nagrzane powietrze będzie mieć Temp +30C. Nie ważne czy jest lato, czy zima. Będziemy mieć wtedy takie same warunki przez prawie cały rok(w lato przy temperaturze >30C nic nie zrobię, no chyba, że zamontuję chłodzenie w Smogomierzu). Pomiary będą wtedy mega miarodajne, bo zawsze przeprowadzane przy takich samych warunkach. Jedyne co się będzie zmieniać ilośc pyłu w powietrzu. Nawet wilgotność pozostanie na w miarę zbliżonych poziomach. 

Na koniec trzeba będzie jeszcze przemyśleć samą obudowę Smogomierza, a dokładniej to rozmieszczenie w nim elementów. Przy grzałce najlepiej korzysta się z miernika SDS011, bo może on pobierać powietrze przez rurkę. W przypadku PMS5003/7003, HPMA115S0-XXX, czy Sensirona SPS30(muszę dodać obsługę do Smogomierza. Mam ich kilka, strasznie je lubię, mają żywotność 8lat, mega dokładne pomiary i kosztują około 130zł) trzeba będzie zaprojektować jakiś system montażu rurki doprowadzającem powietrze do pomiarów. Myślałem o elementach do wydrukowania na drukarce 3D, które zakładałoby się w miejsce wlotu powietrza do czujnika. Te elementy pozwalałyby na podpięcie tam takiej samej rurki jak w przypadku SDS011. Tylko mam tutaj świadomość, że druk 3D trochę ogranicza grono osób, które mogą sobie same złożyć Smogomierz. Nie mam jednak za bardzo pomysłu jak inaczej podłączyć rurkę 4mm do innych mierników. 

Na koniec dochodzi jeszcze najważniejsza kwestia - czas. Ostatnio mam go znacznie mniej. Przez ostatnie 2 miesiące nie miałem go zupełnie dla Smogomierza. Jest kilka rzeczy w oprogramowaniu, które chciałbym poprawić i zmienić. Zmienić trochę interfejs użytkownika i dodać wsparcie dla nowych mierników(np. wspomniany SPS30). Zwyczajnie nie mam kiedy tego zrobić. 

Na koniec zdjęcie Smogomierzy z grzałkami 
![IMG_3563](https://user-images.githubusercontent.com/1752244/72519855-7fc33b00-3858-11ea-85aa-12efae0f59fc.jpg)
