### ISSUE TITLE
nie chce skompilować wersji 2.7.5

### ISSUE THREAD

**Issue by krupniok200** [hackerspace-silesia/Smogomierz#79]
Dziś próbowałem skompilować repo z wersji 2.7.5 i wyskakuje błąd podany w linku, niby za duża ilość bibliotek, ale ja tam nie potrafię się doliczyć, z programem jest wszystko ok, bo poprzednia kompilacja przechodzi bez problemów, biblioteki najnowsze

[Błąd](https://pastebin.com/Z1x9ZjJQ)

**Comment by majstercar** [comment]
Mi pomogło dodanie ręcznie do Arduino bibliotek:ESPAsyncTCP i  ESPAsyncWebServer - Pozdrawiam

**Comment by krupniok200** [comment]
zapodasz jak to zrobiłeś? bo w katalogach bibliotek tego nie widzi mi

**Comment by bfaliszek** [comment]
ESPAsyncTCP - https://github.com/me-no-dev/ESPAsyncTCP
ESPAsyncWebServer - https://github.com/me-no-dev/ESPAsyncWebServer
Pobierasz .zip z biblioteką. W ArduinoIDE dodajesz te .zip z bibliotekami.

**Comment by krupniok200** [comment]
dzięki, działa!

**Comment by bfaliszek** [comment]
Dodałem info o tych bibliotekach do instrukcji - https://github.com/hackerspace-silesia/Smogomierz/blob/master/instrukcje/software.md#arduino---instalacja 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
