### ISSUE TITLE
Róznica miedzy odczytem cisnienia z czujnika a wyswietlanym na aqi.eco

### ISSUE THREAD

**Issue by dudus2000** [hackerspace-silesia/Smogomierz#81]
Znacznie roznia sie dane z czujnika z tymi przedstawianymi na stronie
czy istnieje jakas mozliwosc zniwelowania tej roznicy
w zalacznikach pokazuje jak to u mnie wyglada
![czujnik](https://user-images.githubusercontent.com/9988925/74109345-c4ee3a80-4b82-11ea-9e0d-53d977a96ce8.jpg)
![strona_aqi eco](https://user-images.githubusercontent.com/9988925/74109346-c586d100-4b82-11ea-9246-687068cd7fb0.jpg)

**Comment by krupniok200** [comment]
było to już, ustaw na stronie wysokość 0 i będzie poprawnie

**Comment by bfaliszek** [comment]
https://github.com/hackerspace-silesia/Smogomierz/issues/74#issuecomment-577683928

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
