### ISSUE TITLE
Pomiar napięcia

### ISSUE THREAD

**Issue by m-dudzinski** [hackerspace-silesia/Smogomierz#86]
Cześć, jestem już po budowie własnego egzemplarza, wszystko śmiga aż miło :) Zamówiłem też sobie akumulatorki 18650 razem z modułem ładowania, żeby móc zamontować urządzenie na zewnątrz bez konieczności podciągania do niego kabla. Chciałbym jednak mieć możliwość kontroli zdalnej napięcia, czy jest możliwość implementacji tego w kodzie? Jak podejść do tego tematu?

**Comment by bfaliszek** [comment]
https://github.com/hackerspace-silesia/Smogomierz/issues/56
https://github.com/hackerspace-silesia/Smogomierz/issues/75
Są już dwa Issues o takiej tematyce. Zamykam ten. Najlepiej przenieś tam swoje pytanie.
