### ISSUE TITLE
Kompilacja na ESP32

### ISSUE THREAD

**Issue by ebuke** [hackerspace-silesia/Smogomierz#87]
Cześć,
Po kompilacji w logu mam takie wpisy. Co jest tego powodem? 

In file included from sketch\src\HTU21D.h:49:0,

                 from sketch\src\HTU21D.cpp:32:

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'float HTU21D::readHumidity(HTU21D_HUMD_OPERATION_MODE)':

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'float HTU21D::readTemperature(HTU21D_TEMP_OPERATION_MODE)':

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'uint16_t HTU21D::readDeviceID()':

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'uint8_t HTU21D::readFirmwareVersion()':

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'uint8_t HTU21D::read8(uint8_t)':

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:98:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int address, int size, int sendStop);

C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:93:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)

     uint8_t requestFrom(uint16_t address, uint8_t size, bool sendStop);

Szkic używa 1269758 bajtów (64%) pamięci programu. Maksimum to 1966080 bajtów.
Zmienne globalne używają 63624 bajtów (19%) pamięci dynamicznej, pozostawiając 264056 bajtów dla zmiennych lokalnych. Maksimum to 327680 bajtów.

**Comment by bfaliszek** [comment]
Drobne błędy w zewnętrznej bibliotece do obsługi HTU21D/SHT31. Nie jestem autorem tej biblioteki, tylko z niej korzystam w moim projekcie. Nie wpływają one na kompilację i działanie samego urządzenia, dlatego nic z nimi nie robię. Na końcu nie masz błędu kompilacji. Te info o tylko ostrzeżenia.
