### ISSUE TITLE
Integracja z AZURE IoT Hub

### ISSUE THREAD

**Issue by opennas** [hackerspace-silesia/Smogomierz#9]
Może ktoś już próbował integrować z AZURE IoT? 
Zaczynam dopiero projekt i widzę, że są biblioteki do AZURE.

**Comment by bfaliszek** [comment]
Nigdy nie korzystałem z Azure przy projektach opartych na ESP8266. Znasz może jakiś przykład takiego rozwiązania? Ten opisany tutaj jest ok? https://docs.microsoft.com/pl-pl/azure/iot-hub/iot-hub-arduino-huzzah-esp8266-get-started

**Comment by opennas** [comment]
Właśnie ten analizuję i zastanawiam się jak zintegrować. W AZURE jest ładna prezentacja wyników i można prowadzić rozbudowane analizy na większej ilości czujników o co mi chodzi.
Mamy gotowe 4-5 bibliotek AZURE IoT.
