### ISSUE TITLE
brakujące biblioteki ver 2.7.8

### ISSUE THREAD

**Issue by krupniok200** [hackerspace-silesia/Smogomierz#95]
Czy do kompilacji wersji 2.7.8 trzeba doinstalować biblioteki OneWire oraz DallasTemperature?

**Comment by bfaliszek** [comment]
Dokładnie. Tak jak w opisie. Podpunk 9 - https://github.com/hackerspace-silesia/Smogomierz/blob/master/instrukcje/software.md#arduino---konfiguracja
